begin;

create extension if not exists pg_net with schema extensions;

create table if not exists public.push_suscripciones (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  usuario_id bigint references public.usuarios_bingo(id) on delete cascade,
  recibe_admin boolean not null default false,
  user_agent text,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create index if not exists push_suscripciones_usuario_idx
  on public.push_suscripciones (usuario_id)
  where activo and usuario_id is not null;

create index if not exists push_suscripciones_admin_idx
  on public.push_suscripciones (recibe_admin)
  where activo and recibe_admin;

alter table public.push_suscripciones enable row level security;
revoke all on table public.push_suscripciones from public, anon, authenticated;
revoke all on sequence public.push_suscripciones_id_seq from public, anon, authenticated;

create table if not exists public.bingo_push_config (
  id smallint primary key default 1 check (id = 1),
  function_url text not null,
  webhook_secret text,
  actualizado_en timestamptz not null default now()
);

alter table public.bingo_push_config enable row level security;
revoke all on table public.bingo_push_config from public, anon, authenticated;

insert into public.bingo_push_config (id, function_url)
values (1, 'https://okwkwgrecwxydjcezcdn.supabase.co/functions/v1/bingo-push')
on conflict (id) do update
set function_url = excluded.function_url,
    actualizado_en = now();

create or replace function public.bingo_push_endpoint_valido(p_endpoint text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select
    length(coalesce(p_endpoint, '')) between 20 and 2048
    and (
      p_endpoint ~ '^https://fcm\.googleapis\.com/'
      or p_endpoint ~ '^https://updates\.push\.services\.mozilla\.com/'
      or p_endpoint ~ '^https://push\.services\.mozilla\.com/'
      or p_endpoint ~ '^https://[^/]+\.push\.apple\.com/'
      or p_endpoint ~ '^https://[^/]+\.notify\.windows\.com/'
    );
$$;

create or replace function public.bingo_push_guardar(
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_agent text,
  p_usuario_id bigint default null,
  p_recibe_admin boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.bingo_push_endpoint_valido(p_endpoint)
     or length(coalesce(p_p256dh, '')) not between 20 and 512
     or length(coalesce(p_auth, '')) not between 8 and 512 then
    return jsonb_build_object('ok', false, 'codigo', 'suscripcion_invalida');
  end if;

  insert into public.push_suscripciones (
    endpoint, p256dh, auth, usuario_id, recibe_admin, user_agent, activo, actualizado_en
  )
  values (
    p_endpoint, p_p256dh, p_auth, p_usuario_id, p_recibe_admin,
    left(coalesce(p_user_agent, ''), 500), true, now()
  )
  on conflict (endpoint) do update
  set p256dh = excluded.p256dh,
      auth = excluded.auth,
      usuario_id = coalesce(excluded.usuario_id, public.push_suscripciones.usuario_id),
      recibe_admin = public.push_suscripciones.recibe_admin or excluded.recibe_admin,
      user_agent = excluded.user_agent,
      activo = true,
      actualizado_en = now();

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.bingo_push_suscribir_cliente(
  p_token text,
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usuario_id bigint;
begin
  v_usuario_id := public.bingo_usuario_por_token(p_token);
  if v_usuario_id is null then
    return jsonb_build_object('ok', false, 'codigo', 'sesion_invalida');
  end if;

  return public.bingo_push_guardar(
    p_endpoint, p_p256dh, p_auth, p_user_agent, v_usuario_id, false
  );
end;
$$;

create or replace function public.bingo_push_suscribir_admin(
  p_token text,
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.bingo_admin_requerir_token(p_token);
  return public.bingo_push_guardar(
    p_endpoint, p_p256dh, p_auth, p_user_agent, null, true
  );
end;
$$;

create or replace function public.bingo_push_emitir(p_payload jsonb)
returns void
language plpgsql
security definer
set search_path = public, net
as $$
declare
  v_config public.bingo_push_config%rowtype;
begin
  select * into v_config from public.bingo_push_config where id = 1;
  if v_config.function_url is null or nullif(v_config.webhook_secret, '') is null then
    return;
  end if;

  perform net.http_post(
    url := v_config.function_url,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-bingo-push-secret', v_config.webhook_secret
    ),
    body := p_payload,
    timeout_milliseconds := 5000
  );
exception
  when others then
    raise warning 'No se pudo encolar la notificacion Push: %', sqlerrm;
end;
$$;

create or replace function public.bingo_push_evento_solicitud()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_estado text;
  v_estado_anterior text;
  v_nombre text;
  v_titulo text;
  v_cuerpo text;
  v_url text;
  v_tag text;
  v_usuario_id bigint;
  v_monto numeric;
begin
  v_estado := lower(coalesce(new.estado, ''));
  v_estado_anterior := case when tg_op = 'UPDATE' then lower(coalesce(old.estado, '')) else '' end;
  if tg_op = 'UPDATE' and v_estado = v_estado_anterior then return new; end if;

  if tg_table_name = 'apartados_temp' then
    if v_estado <> 'pendiente' then return new; end if;
    v_nombre := coalesce(nullif(new.nombre, ''), 'Un cliente');
    v_monto := coalesce(new.precio_total, 0);
    perform public.bingo_push_emitir(jsonb_build_object(
      'target', 'admin',
      'title', 'Nueva compra pendiente',
      'body', format('%s envió una compra por %s Bs.', v_nombre, v_monto),
      'url', 'admin.html#ventas',
      'tag', format('compra-%s', new.id)
    ));
    return new;
  end if;

  v_usuario_id := new.usuario_id;
  select coalesce(nullif(u.nombre, ''), 'Un cliente')
    into v_nombre
  from public.usuarios_bingo u
  where u.id = v_usuario_id;
  v_nombre := coalesce(v_nombre, 'Un cliente');

  if tg_table_name = 'recargas_bingo' then
    v_monto := coalesce(new.monto, 0);
    if v_estado = 'pendiente' then
      v_titulo := 'Nueva recarga pendiente';
      v_cuerpo := format('%s solicitó una recarga de %s Bs.', v_nombre, v_monto);
      v_url := 'admin.html#recargas';
      v_tag := format('recarga-admin-%s', new.id);
    elsif v_estado in ('aprobado', 'aprobada') then
      v_titulo := 'Recarga aprobada';
      v_cuerpo := format('Tu recarga de %s Bs fue aprobada. Tu saldo ya está actualizado.', v_monto);
      v_url := 'cuenta.html';
      v_tag := format('recarga-cliente-%s', new.id);
    elsif v_estado in ('rechazado', 'rechazada') then
      v_titulo := 'Recarga rechazada';
      v_cuerpo := format('Tu solicitud de recarga de %s Bs fue rechazada.', v_monto);
      v_url := 'cuenta.html';
      v_tag := format('recarga-cliente-%s', new.id);
    else
      return new;
    end if;
  elsif tg_table_name = 'retiros_bingo' then
    v_monto := coalesce(new.monto, 0);
    if v_estado = 'pendiente' then
      v_titulo := 'Nuevo retiro pendiente';
      v_cuerpo := format('%s solicitó un retiro de %s Bs.', v_nombre, v_monto);
      v_url := 'admin.html#retiros';
      v_tag := format('retiro-admin-%s', new.id);
    elsif v_estado in ('aprobado', 'aprobada') then
      v_titulo := 'Retiro aprobado';
      v_cuerpo := format('Tu retiro de %s Bs fue aprobado. Revisa tu cuenta.', v_monto);
      v_url := 'cuenta.html';
      v_tag := format('retiro-cliente-%s', new.id);
    elsif v_estado in ('rechazado', 'rechazada') then
      v_titulo := 'Retiro rechazado';
      v_cuerpo := format('Tu solicitud de retiro de %s Bs fue rechazada.', v_monto);
      v_url := 'cuenta.html';
      v_tag := format('retiro-cliente-%s', new.id);
    else
      return new;
    end if;
  elsif tg_table_name = 'recuperaciones_pin_bingo' then
    if v_estado = 'pendiente' then
      v_titulo := 'Nueva recuperación de PIN';
      v_cuerpo := format('%s solicitó recuperar su PIN.', v_nombre);
      v_url := 'admin.html#recuperaciones';
      v_tag := format('pin-admin-%s', new.id);
    elsif v_estado = 'aprobado' then
      v_titulo := 'Cambio de PIN aprobado';
      v_cuerpo := 'Tu nuevo PIN fue aprobado. Ya puedes iniciar sesión.';
      v_url := 'login.html';
      v_tag := format('pin-cliente-%s', new.id);
    elsif v_estado = 'rechazado' then
      v_titulo := 'Cambio de PIN rechazado';
      v_cuerpo := 'Tu solicitud para cambiar el PIN fue rechazada. Comunícate con soporte.';
      v_url := 'login.html';
      v_tag := format('pin-cliente-%s', new.id);
    else
      return new;
    end if;
  else
    return new;
  end if;

  if v_estado = 'pendiente' then
    perform public.bingo_push_emitir(jsonb_build_object(
      'target', 'admin', 'title', v_titulo, 'body', v_cuerpo, 'url', v_url, 'tag', v_tag
    ));
  else
    perform public.bingo_push_emitir(jsonb_build_object(
      'target', 'cliente', 'usuario_id', v_usuario_id,
      'title', v_titulo, 'body', v_cuerpo, 'url', v_url, 'tag', v_tag
    ));
  end if;
  return new;
end;
$$;

drop trigger if exists bingo_push_recargas on public.recargas_bingo;
create trigger bingo_push_recargas
after insert or update of estado on public.recargas_bingo
for each row execute function public.bingo_push_evento_solicitud();

drop trigger if exists bingo_push_retiros on public.retiros_bingo;
create trigger bingo_push_retiros
after insert or update of estado on public.retiros_bingo
for each row execute function public.bingo_push_evento_solicitud();

drop trigger if exists bingo_push_recuperaciones on public.recuperaciones_pin_bingo;
create trigger bingo_push_recuperaciones
after insert or update of estado on public.recuperaciones_pin_bingo
for each row execute function public.bingo_push_evento_solicitud();

drop trigger if exists bingo_push_compras on public.apartados_temp;
create trigger bingo_push_compras
after insert or update of estado on public.apartados_temp
for each row execute function public.bingo_push_evento_solicitud();

revoke all on function public.bingo_push_endpoint_valido(text) from public, anon, authenticated;
revoke all on function public.bingo_push_guardar(text, text, text, text, bigint, boolean) from public, anon, authenticated;
revoke all on function public.bingo_push_emitir(jsonb) from public, anon, authenticated;
revoke all on function public.bingo_push_evento_solicitud() from public, anon, authenticated;
revoke all on function public.bingo_push_suscribir_cliente(text, text, text, text, text) from public;
revoke all on function public.bingo_push_suscribir_admin(text, text, text, text, text) from public;

grant execute on function public.bingo_push_suscribir_cliente(text, text, text, text, text)
  to anon, authenticated;
grant execute on function public.bingo_push_suscribir_admin(text, text, text, text, text)
  to anon, authenticated;

notify pgrst, 'reload schema';

commit;
