-- Reduce conexiones y mensajes Realtime sin alterar saldos, compras ni premios.
-- Migracion incremental: es seguro ejecutarla una sola vez despues de las anteriores.

begin;

-- Limite operativo validado para el plan Free.
insert into public.configuracion (clave, valor)
values ('cantidad_cartones_disponibles', '80')
on conflict (clave) do update set valor = excluded.valor;

-- Eventos compactos: la sala ya no escucha cada UPDATE tecnico de bingo_automatico.
create table if not exists public.bingo_eventos_sala (
  id bigint generated by default as identity primary key,
  juego_id bigint,
  tipo text not null,
  datos jsonb not null default '{}'::jsonb,
  creado_en timestamptz not null default now()
);

create index if not exists idx_bingo_eventos_sala_creado
  on public.bingo_eventos_sala (creado_en desc);

alter table public.bingo_eventos_sala enable row level security;

drop policy if exists bingo_eventos_sala_lectura on public.bingo_eventos_sala;
create policy bingo_eventos_sala_lectura
  on public.bingo_eventos_sala
  for select
  to anon, authenticated
  using (true);

revoke all on table public.bingo_eventos_sala from public, anon, authenticated;
grant select on table public.bingo_eventos_sala to anon, authenticated;

-- Un cupo por cuenta. Las filas vencen solas si el navegador desaparece.
create table if not exists public.bingo_sesiones_sala (
  usuario_id integer primary key references public.usuarios_bingo(id) on delete cascade,
  tab_id text not null,
  conectado_en timestamptz not null default now(),
  ultima_senal_en timestamptz not null default now(),
  expira_en timestamptz not null default (now() + interval '75 seconds')
);

create index if not exists idx_bingo_sesiones_sala_expira
  on public.bingo_sesiones_sala (expira_en);

alter table public.bingo_sesiones_sala enable row level security;
revoke all on table public.bingo_sesiones_sala from public, anon, authenticated;

create or replace function public.bingo_cliente_entrar_sala_optimizada(
  p_token text,
  p_tab_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario_id integer;
  v_cedula text;
  v_actual public.bingo_sesiones_sala%rowtype;
  v_activos integer;
  v_limite constant integer := 80;
begin
  v_usuario_id := public.bingo_usuario_por_token(p_token);
  if v_usuario_id is null then
    return jsonb_build_object('ok', false, 'codigo', 'sesion_invalida');
  end if;
  if length(trim(coalesce(p_tab_id, ''))) < 12 then
    return jsonb_build_object('ok', false, 'codigo', 'tab_invalida');
  end if;

  select cedula into v_cedula
    from public.usuarios_bingo
   where id = v_usuario_id;

  if not exists (
    select 1
      from public.cartones_vendidos cv
     where cv.comprador_id = v_usuario_id
        or regexp_replace(coalesce(cv.cedula, ''), '\\D', '', 'g') =
           regexp_replace(coalesce(v_cedula, ''), '\\D', '', 'g')
  ) then
    return jsonb_build_object('ok', false, 'codigo', 'sin_cartones');
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('bingo-capacidad-sala-v1')::bigint
  );

  delete from public.bingo_sesiones_sala where expira_en <= now();

  select * into v_actual
    from public.bingo_sesiones_sala
   where usuario_id = v_usuario_id
   for update;

  if found and v_actual.tab_id <> p_tab_id and v_actual.expira_en > now() then
    return jsonb_build_object(
      'ok', false, 'codigo', 'cuenta_ya_conectada',
      'reintentar_en', greatest(1, ceil(extract(epoch from (v_actual.expira_en - now())))::integer)
    );
  end if;

  if not found then
    select count(*)::integer into v_activos
      from public.bingo_sesiones_sala
     where expira_en > now();
    if v_activos >= v_limite then
      return jsonb_build_object('ok', false, 'codigo', 'sala_llena', 'limite', v_limite);
    end if;
  end if;

  insert into public.bingo_sesiones_sala (
    usuario_id, tab_id, conectado_en, ultima_senal_en, expira_en
  ) values (
    v_usuario_id, p_tab_id, now(), now(), now() + interval '75 seconds'
  )
  on conflict (usuario_id) do update
    set tab_id = excluded.tab_id,
        ultima_senal_en = excluded.ultima_senal_en,
        expira_en = excluded.expira_en;

  select count(*)::integer into v_activos
    from public.bingo_sesiones_sala
   where expira_en > now();

  return jsonb_build_object('ok', true, 'activos', v_activos, 'limite', v_limite);
end;
$$;

create or replace function public.bingo_cliente_latido_sala_optimizada(
  p_token text,
  p_tab_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario_id integer;
begin
  v_usuario_id := public.bingo_usuario_por_token(p_token);
  if v_usuario_id is null then
    return jsonb_build_object('ok', false, 'codigo', 'sesion_invalida');
  end if;

  update public.bingo_sesiones_sala
     set ultima_senal_en = now(), expira_en = now() + interval '75 seconds'
   where usuario_id = v_usuario_id and tab_id = p_tab_id and expira_en > now();

  if not found then
    return jsonb_build_object('ok', false, 'codigo', 'cupo_vencido');
  end if;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.bingo_cliente_salir_sala_optimizada(
  p_token text,
  p_tab_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario_id integer;
begin
  v_usuario_id := public.bingo_usuario_por_token(p_token);
  if v_usuario_id is not null then
    delete from public.bingo_sesiones_sala
     where usuario_id = v_usuario_id and tab_id = p_tab_id;
  end if;
  return jsonb_build_object('ok', true);
end;
$$;

-- Una sola consulta HTTP reemplaza tres consultas y cinco suscripciones de compra.
create or replace function public.bingo_cliente_estado_compra_optimizado(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario_id integer;
  v_programacion jsonb;
  v_vendidos jsonb;
  v_apartados jsonb;
begin
  v_usuario_id := public.bingo_usuario_por_token(p_token);
  if v_usuario_id is null then
    return jsonb_build_object('ok', false, 'codigo', 'sesion_invalida');
  end if;

  v_programacion := public.bingo_estado_programacion();

  select coalesce(jsonb_agg(cv.numero_carton order by cv.numero_carton), '[]'::jsonb)
    into v_vendidos
    from public.cartones_vendidos cv
   where cv.numero_carton between 1 and 80;

  select coalesce(
           jsonb_agg(
             jsonb_build_object(
               'numero_carton', ca.numero_carton,
               'apartado_id', ca.apartado_id,
               'created_at', ca.created_at
             ) order by ca.numero_carton
           ),
           '[]'::jsonb
         )
    into v_apartados
    from public.cartones_apartados ca
   where ca.numero_carton between 1 and 80
     and ca.created_at >= now() - interval '5 minutes';

  return jsonb_build_object(
    'ok', true,
    'programacion', v_programacion,
    'vendidos', v_vendidos,
    'apartados', v_apartados
  );
end;
$$;

-- Incluye la correccion de tipos de Movimientos para que solo haya un SQL pendiente.
create or replace function public.bingo_cliente_movimientos_seguro(p_token text)
returns table (
  id bigint, tipo text, monto numeric, saldo_anterior numeric,
  saldo_nuevo numeric, descripcion text, referencia text, creado_en timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario_id integer;
begin
  v_usuario_id := public.bingo_usuario_por_token(p_token);
  if v_usuario_id is null then
    raise exception 'Sesion de cliente invalida' using errcode = '42501';
  end if;

  return query
    select m.id::bigint, m.tipo::text, m.monto::numeric,
           m.saldo_anterior::numeric, m.saldo_nuevo::numeric,
           m.descripcion::text, m.referencia::text, m.creado_en::timestamptz
      from public.billetera_movimientos m
     where m.usuario_id = v_usuario_id
     order by m.creado_en desc
     limit 100;
end;
$$;

-- Solo genera eventos cuando cambia el estado visible, nunca por los relojes de cada bola.
create or replace function public.bingo_emitir_evento_sala_optimizado()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tipo text;
begin
  if tg_op = 'INSERT' then
    v_tipo := 'estado';
  elsif new.estado = 'finalizado' and old.estado is distinct from new.estado then
    v_tipo := 'final';
  elsif old.premio_fila_ganador_id is distinct from new.premio_fila_ganador_id
     or old.premio_columna_ganador_id is distinct from new.premio_columna_ganador_id then
    v_tipo := 'premio';
  elsif old.estado is distinct from new.estado
     or old.auto_bolas is distinct from new.auto_bolas
     or old.proximo_juego_en is distinct from new.proximo_juego_en then
    v_tipo := 'estado';
  else
    return new;
  end if;

  insert into public.bingo_eventos_sala (juego_id, tipo, datos)
  values (
    new.id,
    v_tipo,
    jsonb_build_object(
      'estado', new.estado,
      'ganador_id', new.ganador_id,
      'premio_fila_ganador_id', new.premio_fila_ganador_id,
      'premio_columna_ganador_id', new.premio_columna_ganador_id,
      'auto_bolas', new.auto_bolas,
      'proximo_juego_en', new.proximo_juego_en
    )
  );

  delete from public.bingo_eventos_sala
   where creado_en < now() - interval '2 days';

  if v_tipo = 'final' then
    delete from public.bingo_sesiones_sala;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_bingo_evento_sala_optimizado on public.bingo_automatico;
create trigger trg_bingo_evento_sala_optimizado
after insert or update on public.bingo_automatico
for each row execute function public.bingo_emitir_evento_sala_optimizado();

-- El limite de 80 tambien se valida en servidor, no solo en la pantalla.
create or replace function public.bingo_reservar_cartones_seguro(
  p_token text,
  p_cartones integer[],
  p_promocion_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario public.usuarios_bingo%rowtype;
  v_usuario_id integer;
  v_cantidad integer;
  v_precio_total numeric;
  v_precio_unitario numeric;
begin
  v_usuario_id := public.bingo_usuario_por_token(p_token);
  if v_usuario_id is null then
    return jsonb_build_object('ok', false, 'codigo', 'sesion_invalida');
  end if;

  select * into v_usuario
    from public.usuarios_bingo
   where id = v_usuario_id and activo = true;
  if not found then
    return jsonb_build_object('ok', false, 'codigo', 'sesion_invalida');
  end if;

  select count(*) into v_cantidad
    from (select distinct x from unnest(coalesce(p_cartones, '{}'::integer[])) x) s;

  if v_cantidad < 1
     or v_cantidad > 80
     or v_cantidad <> coalesce(array_length(p_cartones, 1), 0)
     or exists (select 1 from unnest(p_cartones) x where x < 1 or x > 80) then
    return jsonb_build_object('ok', false, 'codigo', 'cartones_invalidos');
  end if;

  if p_promocion_id is not null then
    select precio into v_precio_total
      from public.promociones_cartones
     where id = p_promocion_id and activa = true and cantidad = v_cantidad;
    if not found then
      return jsonb_build_object('ok', false, 'codigo', 'promocion_invalida');
    end if;
  else
    select case when valor ~ '^[0-9]+([.,][0-9]+)?$'
                then replace(valor, ',', '.')::numeric else null end
      into v_precio_unitario
      from public.configuracion
     where clave = 'precio_carton';
    if coalesce(v_precio_unitario, 0) <= 0 then
      return jsonb_build_object('ok', false, 'codigo', 'precio_no_configurado');
    end if;
    v_precio_total := round(v_precio_unitario * v_cantidad, 2);
  end if;

  return public.bingo_reservar_cartones(
    v_usuario.id, v_usuario.nombre, v_usuario.telefono, v_usuario.cedula,
    '', p_cartones, v_precio_total, p_promocion_id
  );
end;
$$;

-- El administrador no puede elevar accidentalmente el inventario por encima de 80.
create or replace function public.bingo_admin_guardar_config_seguro(
  p_token text,
  p_clave text,
  p_valor text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_cantidad integer;
begin
  perform public.bingo_admin_requerir_token(p_token);
  if p_clave not in ('precio_carton', 'rotacion_cartones', 'cantidad_cartones_disponibles') then
    return jsonb_build_object('ok', false, 'codigo', 'clave_no_permitida');
  end if;

  if p_clave = 'cantidad_cartones_disponibles' then
    if coalesce(p_valor, '') !~ '^[0-9]+$' then
      return jsonb_build_object('ok', false, 'codigo', 'cantidad_invalida');
    end if;
    v_cantidad := p_valor::integer;
    if v_cantidad < 1 or v_cantidad > 80 then
      return jsonb_build_object('ok', false, 'codigo', 'limite_80_cartones');
    end if;
  end if;

  insert into public.configuracion (clave, valor)
  values (p_clave, left(p_valor, 40))
  on conflict (clave) do update set valor = excluded.valor;
  return jsonb_build_object('ok', true);
end;
$$;

do $publication$
begin
  if not exists (
    select 1 from pg_catalog.pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public'
       and tablename = 'bingo_eventos_sala'
  ) then
    alter publication supabase_realtime add table public.bingo_eventos_sala;
  end if;
end;
$publication$;

revoke all on function public.bingo_cliente_entrar_sala_optimizada(text, text) from public, anon, authenticated;
revoke all on function public.bingo_cliente_latido_sala_optimizada(text, text) from public, anon, authenticated;
revoke all on function public.bingo_cliente_salir_sala_optimizada(text, text) from public, anon, authenticated;
revoke all on function public.bingo_cliente_estado_compra_optimizado(text) from public, anon, authenticated;

grant execute on function public.bingo_cliente_entrar_sala_optimizada(text, text) to anon, authenticated;
grant execute on function public.bingo_cliente_latido_sala_optimizada(text, text) to anon, authenticated;
grant execute on function public.bingo_cliente_salir_sala_optimizada(text, text) to anon, authenticated;
grant execute on function public.bingo_cliente_estado_compra_optimizado(text) to anon, authenticated;
grant execute on function public.bingo_cliente_movimientos_seguro(text) to anon, authenticated;
grant execute on function public.bingo_reservar_cartones_seguro(text, integer[], bigint) to anon, authenticated;
grant execute on function public.bingo_admin_guardar_config_seguro(text, text, text) to anon, authenticated;

notify pgrst, 'reload schema';

commit;
